# Generated by Django 4.0.1 on 2022-02-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import playground.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='mento',
        ),
        migrations.AddField(
            model_name='room',
            name='mentor',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, default=playground.models.set_limit),
        ),
    ]
