# Generated by Django 4.0.1 on 2022-02-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_mentee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='mentee',
            new_name='user',
        ),
    ]
