# Generated by Django 4.0.1 on 2022-02-16 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0004_rename_mentee_mentee_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='MentorRoom',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='room',
            new_name='mentor_room',
        ),
    ]
